// Assignment_4/src/pages/Register.vue
<template>
    <div class="container">
      <h1>Register</h1>
      <Form @on-submit="handleSubmit" :isRegister="true" />
    </div>
  </template>
  
  <script lang="ts">
  interface Credentials {
  username: string;
  password: string;
}

  import { defineComponent } from 'vue';
  import * as api from '../api/gameapi'
  import Form from '../components/Form.vue'; 
  
  export default defineComponent({
    components: {
      Form,
    },
    methods: {
      async handleSubmit(credentials: Credentials) {
        api.createUser(credentials.username, credentials.password)
        this.$router.push('/');
      },
    },
  });
  </script>
  
  <style scoped>

  </style>

// Assignment_3/src/pages/Register.tsx
import { useState } from "react";
import { createUser } from "../api/gameapi";
import { useNavigate } from "react-router-dom";
import Form from "../components/Form";

const RegisterPage = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  let navigate = useNavigate();

  const handleSubmit = async (credentials: {
    username: string;
    password: string;
  }) => {
    try {
      await createUser(credentials.username, credentials.password);
      navigate("/");
    } catch (error) {
      alert("Register failed");
    }
  };

  return (
    <div className="container">
      <h1>Register</h1>
      <Form onSubmit={handleSubmit} isRegister={true} />
    </div>
  );
};

export default RegisterPage;
