// Assignment_3/src/components/HighScoreTable.tsx
import { GameModel } from "../models/apiModels";

interface HighScoreTableProps {
  games: GameModel[];
}

const HighScoreTable: React.FC<HighScoreTableProps> = ({ games }) => {
  return (
    <table>
      <tbody>
        {games.map((game, index) => {
          return (
            <tr key={index} style={{ fontSize: index === 0 ? "30px" : "16px" }}>
              <td>{index + 1}.</td>
              <td>{game.score}</td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};

export default HighScoreTable;

// Assignment_4/src/components/HighScoreTable.vue
<script lang="ts">
import { GameModel } from '../models/apiModels'
export default{
    props: {
        games: {
            type: Array<GameModel>,
            default: []
        }
    }
}
</script>

<template>
    <table>
        <tbody
            v-for="game in games">
            <tr :style="`font-size: ${games.indexOf(game) === 0 ? 30 : 16}px`">
                <td>{{games.indexOf(game) + 1}}.</td>
                <td>{{game.score}}</td>
            </tr>
        </tbody>
    </table>
</template>
