// Assignment_3/src/components/NavButton.tsx
import React from "react";
import { Link } from "react-router-dom";

interface NavButtonProps {
  to: string;
  label: string;
}

const NavButton: React.FC<NavButtonProps> = ({ to, label }) => (
  <Link to={to}>
    <button className="button">{label}</button>
  </Link>
);

export default NavButton;

// Assignment_4/src/components/NavButton.vue
<template>
    <router-link :to="to || '/'">
      <button class="button">{{ label }}</button>
    </router-link>
</template>
  
  <script lang="ts">
  export default {
    props: {
      to: String,
      label: String,
    },
  };
  </script>
  
  <style scoped>
  /* Your component-specific styles */
  </style>
