// Assignment_4/src/components/AuthNav.vue
<template>
      <NavButton to="/menu" label="Menu" />
      <NavButton to="/highscore" label="High Scores" />
      <NavButton to="/profile" label="My Profile" />
      <router-link to="/" @click="onLogout">
        <button class="button">Logout</button>
      </router-link>
  </template>
  
  <script lang="ts">
  import NavButton from "./NavButton.vue";
  
  export default {
    props: {
      onLogout: Function,
    },
    components: {
      NavButton,
    },
  };
  </script>
  
  <style scoped>
  /* Your component-specific styles */
  </style>

// Assignment_3/src/components/AuthNav.tsx
import React from "react";
import { Link } from "react-router-dom";
import NavButton from "./NavButton";

interface AuthNavProps {
  onLogout: () => void;
}

const AuthNav: React.FC<AuthNavProps> = ({ onLogout }) => (
  <>
    <NavButton to="/menu" label="Menu" />
    <NavButton to="/highscore" label="High Scores" />
    <NavButton to="/profile" label="My Profile" />
    <Link to="/" onClick={onLogout}>
      <button className="button">Logout</button>
    </Link>
  </>
);

export default AuthNav;
