// Assignment_4/src/components/FormGroup.vue
<template>
    <div class="form-group">
      <label class="form-label">{{ label }}</label>
      <div class="input">
        <input
          class="form-input"
          :type="inputType"
          :value="value"
          @input="(event: Event) => onChange && onChange(event as InputEvent)"
        />
        <button
          v-if="isPassword"
          class="eye-icon"
          @click="toggleShowPassword"
          type="button"
        >
          <i v-if="showPassword" class="material-icons">visibility_off</i>
          <i v-else class="material-icons">visibility</i>
        </button>
      </div>
    </div>
  </template>
  
  <script lang="ts">
  export default {
    props: {
      label: String,
      value: String,
      isPassword: {
        type: Boolean,
        default: false,
      },
      onChange: Function,
    },
    data() {
      return {
        showPassword: false,
      };
    },
    computed: {
      inputType() {
        return this.showPassword ? "text" : this.isPassword ? "password" : "text";
      },
    },
    methods: {
      toggleShowPassword() {
        this.showPassword = !this.showPassword;
      },
    },
  };
  </script>
  
  <style scoped>
  /* Your component-specific styles */
  </style>

// Assignment_3/src/components/FormGroup.tsx
import React, { ChangeEvent, useState } from "react";

interface FormGroupProps {
  label: string;
  value: string;
  isPassword?: boolean;
  onChange: (event: ChangeEvent<HTMLInputElement>) => void;
}

const FormGroup: React.FC<FormGroupProps> = ({
  label,
  value,
  onChange,
  isPassword = false,
}) => {
  const [showPassword, setShowPassword] = useState(false);
  const inputType = showPassword ? "text" : isPassword ? "password" : "text";

  return (
    <div className="form-group">
      <label className="form-label">{label}</label>
      <div className="input">
        <input
          className="form-input"
          type={inputType}
          value={value}
          onChange={onChange}
        />
        {isPassword && (
          <button
            className="eye-icon"
            onClick={() => setShowPassword(!showPassword)}
            type="button"
          >
            {showPassword ? (
              <i className="material-icons">visibility_off</i>
            ) : (
              <i className="material-icons">visibility</i>
            )}
          </button>
        )}
      </div>
    </div>
  );
};

export default FormGroup;
