// Assignment_3/src/components/board.tsx
import * as React from  'react';
import Image from './Image';
import { Position, move, Generator, create, Board } from '../models/board';
import { useAppDispatch, useAppSelector } from '../config/store';
import { setInitialBoardGame, boardMoveUpdate } from '../reducers/gameReducer';
import { createGame, updateGame } from '../api/gameapi';
import { GameModel } from '../models/apiModels';

class RandomGenerator implements Generator<string> {
    images: string[] = ["../images/cat1.png", "../images/cat2.png", "../images/cat3.png", "../images/cat4.png", "../images/cat5.jpg"]
    
    next(): string {
        return this.images[Math.floor(Math.random() * this.images.length)]
    }
}
const generator: RandomGenerator = new RandomGenerator()

const mapToModel = (result: any): GameModel => {
    return {
        id: result.id,
        user: result.user,
        score: result.score,
        completed: result.completed
    }
}

const BoardGame: React.FC = () => {
    const game = useAppSelector((state) => state.gameReducer)
    const user = useAppSelector((state) => state.userReducer)
    const dispatch = useAppDispatch();
    const [selectedPosition, setSelectedPosition] = React.useState<Position>(undefined)

    if (game.board === undefined)
    {
        createGame(user.token).then(result => { 
            var game = mapToModel(result)
            dispatch(setInitialBoardGame({board: create(generator, 6, 6), gameId: game.id}))
        }).catch(_ => alert("Could create a new game"))
    }

    const selectTile = async (ir : number, ic : number) => {
        if (game.currentMoveNumber < game.maxMoveNumber) {
            if (selectedPosition === undefined)
            {
                setSelectedPosition({row: ir, col: ic})
            }
            else
            {
                const newBoard: Board<string> = JSON.parse(JSON.stringify(game.board))
                const result = move(generator, newBoard, selectedPosition, {row: ir, col: ic})
                if (result.effects.length > 0)
                {
                    const score = result.effects.filter(effect => effect.kind == "Match").length * 5;
                    dispatch(boardMoveUpdate({board: result.board, score: score}))
                }
                setSelectedPosition(undefined)
            }
        }
    }

    React.useEffect(() => {
        if (game.currentMoveNumber < game.maxMoveNumber) 
        {
            updateGame(user.token, {id: game.gameId, user: user.id, score: game.score, completed: false}).catch(_ => alert("Could not update the game"))
        } 
        else 
        {
            updateGame(user.token, {id: game.gameId, user: user.id, score: game.score, completed: true}).catch(_ => alert("Could not update the game"))
        }
    }, [game.currentMoveNumber, game.score])

    const resetGame = async () => {
        setSelectedPosition(undefined)
        createGame(user.token).then(result => { 
            var game = mapToModel(result)
            dispatch(setInitialBoardGame({board: create(generator, 6, 6), gameId: game.id}))
        }).catch(_ => alert("Could create a new game"))  
    }

    return (
        <div className='board'>
            <table>
                <tbody>
                    {game.board.pieces.map((row, ir) => { return (
                        <tr key={ir}>
                            {row.map((col, ic) => { return (
                                <td key={ic} className={`tile ${selectedPosition && selectedPosition.col == ic && selectedPosition.row == ir ? "selected-tile" : ""}`} onClick={() => selectTile(ir, ic)}>
                                    <Image src={col}/>
                                </td>)
                            })}
                        </tr>)
                    })}
                </tbody>
            </table>
            <button className='reset-button' onClick={() => resetGame()}>Reset</button>
        </div>
    )
}

export default BoardGame;

// Assignment_4/src/pages/Board.vue
<script setup lang="ts">
    import { getGame, updateGame } from '../api/gameapi'
    import Score from '../components/Score.vue'
    import { Position, move, Board } from '../models/board'
    import { model, generator } from '../models/store'
    import { onMounted, reactive } from 'vue'

    const maxMoveNumber = 25;
    let selectedPosition = reactive<Position>({}); 

    onMounted(async () => {
        if (model.game.id === -1 && parseInt(localStorage.getItem("gameId") ?? '-1')) {
            model.game = await getGame(model.token, model.game.id)
        }
        if (model.game.id === -1) {
            return;
        }
        await onMoveUpdate();
        
    });

    const onMoveUpdate = async () => {
        if (model.game.currentMoveNumber < maxMoveNumber) {
            await updateGame(model.token, model.game)
        } else if (model.game.id !== -1) {
            model.game.completed = true
            // update game
            await updateGame(model.token, model.game)
        }
    }

    const selectTile = async (ir: number, ic: number) => {
        if (model.game.currentMoveNumber < maxMoveNumber) {
            if (selectedPosition === undefined) {
                selectedPosition = ({ row: ir, col: ic });
            } else {
                await setSelectTile(selectedPosition, ir, ic);
                selectedPosition = {};
            }
        }
    }

    const setSelectTile = async (selectedPosition: Position, ir: number, ic: number) => {
        try {
            const newBoard: Board<string> = JSON.parse(JSON.stringify(model.game.board));
            const result = move(generator, newBoard, selectedPosition, {
                row: ir,
                col: ic
            });
            if (result.effects.length > 0) {
                const score = result.effects.filter((effect) => effect.kind == "Match").length * 5;
                await onMoveUpdate();
                model.updateBoard(result.board, score);
            }
        } 
        catch (error) 
        { alert("Could not make move");}
    }

</script>

<template>
    <div>
      <Score
        :score="model.game.score"
        :max-move-number= "maxMoveNumber"
        :current-move-number= "model.game.currentMoveNumber"
      />
      <div className="board-container">
        <div className="board">
          <table>
            <tbody>
              <tr v-for= "(row, ir) in model.game.board?.pieces" :key="ir">
                <td
                  v-for="(col, ic) in row" :key = "ic" :class="`tile ${{
                            selectedPosition &&
                            selectedPosition.col == ic &&
                            selectedPosition.row == ir
                              ? 'selected-tile'
                              : ''
                          }}`" @onClick = "() => selectTile(ir, ic)">
                        <Image :src="col" />
                  </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
</template>
