// Assignment_3/src/pages/HighScore.tsx
import { GameModel } from "../models/apiModels";
import { useAppSelector } from "../config/store";
import { useEffect, useState } from "react";
import HighScoreTable from "../components/HighScoreTable";

const HighScorePage = () => {
  const user = useAppSelector((state) => state.userReducer);
  const game = useAppSelector((state) => state.gameReducer);
  const [games, setGames] = useState<GameModel[]>([]);

  useEffect(() => {
    if (game.games) {
      setGames(game.games);
    }
  }, [game.games]);

  const top10Games = games
    .filter((game) => game.completed)
    .sort((a, b) => b.score - a.score)
    .slice(0, 10);

  const top3OwnGames = games
    .filter((game) => game.user == user.id && game.completed)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);

  return (
    <div className="highscores">
      {top10Games.length !== 0 && (
        <>
          <h3 className="bigger-font">High scores</h3>
          <HighScoreTable games={top10Games} />
        </>
      )}
      <br />
      {top3OwnGames.length !== 0 && (
        <>
          {" "}
          <h3>Top 3 high scores</h3>
          <HighScoreTable games={top3OwnGames} />
        </>
      )}
    </div>
  );
};
export default HighScorePage;

// Assignment_4/src/pages/HighScore.vue
<script lang="ts">
    import * as api from '../api/gameapi'
    import { model } from "../models/store"
    import HighScoreTable from '../components/HighScoreTable.vue';
    import { GameModel } from '../models/apiModels';

    export default {
        data() {
            return { 
                model,
                top10Games: [],
                top3OwnGames: [] 
            }
        },
        components: {
        HighScoreTable,
        },
        mounted() {
            if (model.token !== undefined) {
                api.getAllGames(model.token).then((result: GameModel[]) => {
                    model.games = result
                })
            }
        }
    }
</script>

<template>
    <div class="highscores">
        <h3 className="bigger-font">High scores</h3>
        <HighScoreTable :games="model.games.filter((game) => game.completed).sort((a, b) => b.score - a.score).slice(0, 10)"/>
        <br />
        <h3>Top 3 high scores</h3>
        <HighScoreTable :games="model.games.filter((game) => game.user == model.user.id && game.completed).sort((a, b) => b.score - a.score).slice(0, 3)" />
  </div>
</template>
