// Assignment_3/src/pages/Login.tsx
import { loginUser } from "../api/gameapi";
import { useNavigate } from "react-router-dom";
import { useAppDispatch } from "../config/store";
import Form from "../components/Form";
import LoginLink from "../components/LoginLink";
import { login } from "../reducers/game";

const LoginPage: React.FC = () => {
  let navigate = useNavigate();
  const dispatch = useAppDispatch();

  const handleLogin = async (credentials: {
    username: string;
    password: string;
  }) => {
    try {
      await loginUser(credentials.username, credentials.password).then(result => {
        if (result.token) {
          dispatch(login(result))
          navigate("/board");
        }
      })
    } catch (error) {
      alert("Login failed");
    }
  };

  return (
    <div className="container">
      <h1>Login</h1>
      <Form onSubmit={handleLogin} />
      <LoginLink />
    </div>
  );
};

export default LoginPage;

// Assignment_4/src/pages/Login.vue
<template >
  <div class="container">
    <h1>Login</h1>
    <Form @on-submit="handleLogin" />
    <LoginLink />
  </div>
</template>
  
<script lang="ts">
import Form from "../components/Form.vue"; 
import LoginLink from "../components/LoginLink.vue";
import * as api from '../api/gameapi'
import { model } from '../models/store'

interface Credentials {
  username: string;
  password: string;
}

export default {
  components: {
    Form,
    LoginLink,
  },
  methods: {
    handleLogin(credentials: Credentials) {
      api.loginUser(credentials.username, credentials.password).then((result) => {
                if (result) {
                    model.login(result.userId, result.token);
                    this.$router.push('/menu');
                }
            });
    },
  },
};
</script>

<style scoped>

</style>
